cask_args appdir: '/Applications'
tap 'caius/prince'
tap 'colindean/fonts-nonfree'
tap 'datawire/blackbird'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'nodenv/nodenv'
tap 'wagoodman/dive'
tap 'lautis/refined-github-safari'
tap 'lautis/tap'

brew 'mas'

mas 'Xcode', id: 497799835
mas 'Airmail 3', id: 918858936
mas 'iA Writer', id: 775737590
mas 'Pixelmator', id: 407963104
mas 'Pages', id: 409201541
mas 'Numbers', id: 409203825
mas 'Keynote', id: 409183694
mas 'Telegram', id: 747648890
mas 'The Unarchiver', id: 425424353
mas 'DaisyDisk', id: 411643860
mas 'Amphetamine', id: 937984704
mas '1Blocker', id: 1365531024
mas 'Giphy Capture', id: 668208984
mas 'Agenda', id: 1287445660
mas 'Smart Guide', id: 1394121296
mas 'TweetBot 3', id: 1384080005
mas 'PiPifier', id: 1160374471
mas 'Refined Github', id: 1519867270

brew 'angle-grinder'
brew 'bat'
brew 'docker-clean'
brew 'emojify'
brew 'exa'
brew 'dive'
brew 'fasd'
brew 'fd'
brew 'fzf'
brew 'fx'
brew 'gifski'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'htop'
brew 'hub'
brew 'imagemagick'
brew 'jenv'
brew 'jpegoptim'
brew 'jq'
brew 'kubernetes-cli'
brew 'libpq'
brew 'mobile-shell'
brew 'nano'
brew 'node-build'
brew 'nodenv'
brew 'nodenv/nodenv/node-build-update-defs'
brew 'nodenv/nodenv/nodenv-default-packages'
brew 'p7zip'
brew 'pngcrush'
brew 'prince'
brew 'python'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'rbenv-vars'
brew 'readline'
brew 'ripgrep'
brew 'ruby-build'
brew 'rustup-init'
brew 'socat'
brew 'sshuttle'
brew 'starship'
brew 'telepresence'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tldr'
brew 'tokei'
brew 'tmux'
brew 'tmuxinator'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'yarn'

cask 'charles'
cask 'docker'
cask 'dropshare'
cask 'firefox'
cask 'fork'
cask 'font-fira-code'
cask 'font-hasklig'
cask 'font-menlo-for-powerline'
cask 'font-microsoft-office'
cask 'font-office-code-pro'
cask 'font-offlig'
cask 'google-chrome'
cask 'gpg-suite'
cask 'hex-fiend'
cask 'insomnia'
cask 'numi'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'paintbrush'
cask 'rectangle'
cask 'spotify'
cask 'transmission'
cask 'transmit'
cask 'visual-studio-code'
cask 'vlc'
cask 'webpquicklook'
