right_format = """$cmd_duration$status"""
add_newline = true

[status]
disabled = false
format = "[$status$symbol]($style) "


[nodejs]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[python]
disabled = true

[rust]
disabled = true
